import './cwc-capture-box.js';
import './cwc-capture-checkbox.js';
import './cwc-capture-date.js';
import './cwc-capture-input.js';
import './cwc-capture-radio.js';
import './cwc-capture-select.js';
import './cwc-capture-switch.js';
import './cwc-capture-time.js';
import './cwc-capture-year.js';
